/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";

export function Model(props) {

 
 
   const nombreGBL = props.nombre

    const { nodes, materials } = useGLTF("/public/models/" + nombreGBL);
    
    const escala = props.escala
  return (
    <group {...props} dispose={null}>
    <mesh
      castShadow
      receiveShadow
    
      geometry={nodes.props.nombreGeometria.geometry}
      material={materials.props.material}
      scale={escala}
    />
    </group>
  );
}
useGLTF.preload("/PizzaVegieZ.glb");
